export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const POSITION_SIDEBAR = 'POSITION_SIDEBAR';
export const TOGGLE_OPEN_SIDEBAR = 'TOGGLE_OPEN_SIDEBAR';
export const CHANGE_ACTIVE_SIDEBAR_ITEM = 'CHANGE_ACTIVE_SIDEBAR_ITEM';
